Vagrant::Config.run do |config|
  config.vm.box = 'puppetmaster'
  config.vm.box_url = '/Users/wagnerza/vagrant-centos55-64bits.box'
  config.vm.boot_mode = :gui

  config.vm.define :sandbox do |puppetmaster|
    puppetmaster.vm.host_name = 'puppetmaster'
    puppetmaster.vm.network "33.33.33.33"

    puppetmaster.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

  # config.vm.define :db do |db_sandbox|
  #   db_sandbox.vm.host_name = 'db_sandbox'
  #   db_sandbox.vm.network "33.33.33.33"
  # 
  #   # db_sandbox.vm.provision :puppet do |puppet|
  #   #       puppet.module_path = ['puppet/modules','puppet-master/modules']
  #   #       puppet.manifest_file = 'site.pp'
  #   #       puppet.options = %w[--templatedir templates]
  #   #     end
  # end


end
