Vagrant::Config.run do |config|
  config.vm.box = 'puppetmaster'
  config.vm.box_url = '/Users/wagnersza/Downloads/centos-56-x86_64.box'
  config.vm.boot_mode = :gui

  config.vm.define :puppetmaster do |puppetmaster|
    puppetmaster.vm.host_name = 'puppetmaster'
    puppetmaster.vm.network "33.33.33.33"
  
    puppetmaster.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

  config.vm.define :puppetclient do |puppetclient|
    puppetclient.vm.host_name = 'puppetclient'
    puppetclient.vm.network "33.33.33.34"
  
    puppetclient.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

end
