Vagrant::Config.run do |config|
  config.vm.box = 'centos-64'
  config.vm.box_url = 'http://dl.dropbox.com/u/40185152/CentOS-5.6-x86_64.box'
  #config.vm.boot_mode = :gui

  # Puppet Server
  config.vm.define :puppetmaster do |puppetmaster|
    puppetmaster.vm.host_name = 'puppetmaster'
    puppetmaster.vm.network "33.33.33.33"
  
    puppetmaster.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

  # Puppet Client
  config.vm.define :puppetclient do |puppetclient|
    puppetclient.vm.host_name = 'puppetclient'
    puppetclient.vm.network "33.33.33.34"
  
    puppetclient.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

  # Nginx
  config.vm.define :nginx do |nginx|
    nginx.vm.host_name = 'nginx'
    nginx.vm.network "33.33.33.35"
  
    nginx.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

  # Rpmmaker
  config.vm.define :rpmmaker do |rpmmaker|
    rpmmaker.vm.host_name = 'rpmmaker'
    rpmmaker.vm.network "33.33.33.36"
  
    rpmmaker.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end
  
  # ControlTier Server
  config.vm.define :controltier_server do |controltier_server|
    controltier_server.vm.host_name = 'controltier_server'
    controltier_server.vm.network "33.33.33.37"
  
    controltier_server.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end
  
  # ControlTier Client
  config.vm.define :controltier_client do |controltier_client|
    controltier_client.vm.host_name = 'controltier_client'
    controltier_client.vm.network "33.33.33.38"
  
    controltier_client.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end

  # DeployInator
  config.vm.define :deployinator do |deployinator|
    deployinator.vm.host_name = 'deployinator'
    deployinator.vm.network "33.33.33.39"
  
    deployinator.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = %w[--templatedir templates]
    end
  end


end
